awesome: &awesome Symbols Nerd Font Mono:style=solid:pixelsize=18
sans: &sans JetBrains Mono:pixelsize=17:style=semibold, Hiragino Sans GB W3:pixelsize=16
bar_cmd: &bar_cmd ~/Dotfiles/scripts/bars

bar:
  # monitor: DP-4
  monitor: eDP-1
  layer: bottom
  height: 32
  location: top
  spacing: 15
  margin: 5

  font: Terminess Nerd Font:style:Bold:pixelsize=18:antialias=true:autohint:true, Cantarell:pixelsize=16, Hiragino Sans GB W3:pixelsize=16, Symbols Nerd Font Mono:pixelsize=18
  background: 1e1e2e99
  foreground: f8f8f2ff


  left:
    - script:
        poll-interval: 300
        path: *bar_cmd
        args: ["aspace"]
        anchors:
          - focused: &focused {deco: {underline: {size: 2, color: ffffffff}}}
          - occupied: &occupied {foreground: ffffffff}
          - default: &default {foreground: cccccc99}
          - map: &mbase
              margin: 10

        content:
          - map:
              <<: *mbase
              default: { string: { text: "{space_1}", <<: *default }}
              on-click: hyprctl dispatch workspace {space_1}
              conditions:
                space_1_focused: { string: { text: "{space_1}", <<: *focused }}
                space_1_occupied: { string: { text: "{space_1}", <<: *occupied }}

          - map:
              <<: *mbase
              default: { string: { text: "{space_2}", <<: *default }}
              on-click: hyprctl dispatch workspace {space_2}
              conditions:
                space_2_focused: { string: { text: "{space_2}", <<: *focused }}
                space_2_occupied: { string: { text: "{space_2}", <<: *occupied }}

          - map:
              <<: *mbase
              default: { string: { text: "{space_3}", <<: *default }}
              on-click: hyprctl dispatch workspace {space_3}
              conditions:
                space_3_focused: { string: { text: "{space_3}", <<: *focused }}
                space_3_occupied: { string: { text: "{space_3}", <<: *occupied }}

          - map:
              <<: *mbase
              default: { string: { text: "{space_4}", <<: *default }}
              on-click: hyprctl dispatch workspace {space_4}
              conditions:
                space_4_focused: { string: { text: "{space_4}", <<: *focused }}
                space_4_occupied: { string: { text: "{space_4}", <<: *occupied }}

          - map:
              <<: *mbase
              default: { string: { text: "{space_5}", <<: *default }}
              on-click: hyprctl dispatch workspace {space_5}
              conditions:
                space_5_focused: { string: { text: "{space_5}", <<: *focused }}
                space_5_occupied: { string: { text: "{space_5}", <<: *occupied }}

          - map:
              <<: *mbase
              default: { string: { text: "{space_6}", <<: *default }}
              on-click: hyprctl dispatch workspace {space_6}
              conditions:
                space_6_focused: { string: { text: "{space_6}", <<: *focused }}
                space_6_occupied: { string: { text: "{space_6}", <<: *occupied }}

          - map:
              <<: *mbase
              default: { string: { text: "{space_7}", <<: *default }}
              on-click: hyprctl dispatch workspace {space_7}
              conditions:
                space_7_focused: { string: { text: "{space_7}", <<: *focused }}
                space_7_occupied: { string: { text: "{space_7}", <<: *occupied }}

          - map:
              <<: *mbase
              default: { string: { text: "{space_8}", <<: *default }}
              on-click: hyprctl dispatch workspace {space_8}
              conditions:
                space_8_focused: { string: { text: "{space_8}", <<: *focused }}
                space_8_occupied: { string: { text: "{space_8}", <<: *occupied }}

          - map:
              <<: *mbase
              default: { string: { text: "{space_9}", <<: *default }}
              on-click: hyprctl dispatch workspace {space_9}
              conditions:
                space_9_focused: { string: { text: "{space_9}", <<: *focused }}
                space_9_occupied: { string: { text: "{space_9}", <<: *occupied }}

    - script:
        poll-interval: 1000
        path: *bar_cmd
        args: ["awin"]
        content: 
          string: 
            max: 50
            text: "{title}" 
            font: *sans 

  right:

    - script:
        poll-interval: 5000
        path: *bar_cmd
        args: ["music"]
        content:
          map:
            conditions:
              status == "Playing":
                string: 
                  text: "\uf04b {artist} - {title}"
                  on-click: sh -c "playerctl pause"
              status == "Paused":
                string: 
                  text: "\uf04c {artist} - {title}"
                  on-click: sh -c "playerctl play"

    - script:
        poll-interval: 10000
        path: *bar_cmd
        args: ["timew"]
        content:
          map:
            conditions:
              running:
                string: 
                  text: "\uf017 {interval} {tag}" 
                  on-click: sh -c "timew stop"

    - script:
        poll-interval: 10000
        path: *bar_cmd
        args: ["tasks"]
        content: { string: { text: "\uf024 {count}" }}

    - script:
        poll-interval: 10000
        path: *bar_cmd
        args: ["mail"]
        content: { string: { text: "\uf0e0 {unreads}" }}

    - mem:
       poll-interval: 2500
       content:
         string: {text: "{used:gb}GB"}

    - cpu:
       poll-interval: 2500
       content:
         map:
           conditions:
             id < 0:
               - string: {text: "\uf0d8"}
               - string: {text: " {cpu:02}%"}
    - battery:
        name: BAT0
        poll-interval: 30000
        content:
          string: {text: " {capacity}%"}
    - pulse:
        content: 
          string: 
            text: "\uf027 {sink_percent}% ({sink_port})"
            on-click: pavucontrol

    - network:
        poll-interval: 1000
        content:
          map:
            default: {empty: {}}
            conditions:
              name == wlp2s0:
                map:
                  default: {string: {text: , font: *awesome, foreground: ffffff66}}
                  conditions:
                    state == down: {string: {text: , font: *awesome, foreground: ff0000ff}}
                    state == up:
                      map:
                        default:
                          - string: {text: , font: *awesome}
                          - string: {text: "  {ssid}"}

                        conditions:
                          ipv4 == "":
                            - string: {text: , font: *awesome, foreground: ffffff66}
                            - string: {text: "  {ssid}", foreground: ffffff66}

    - script:
        poll-interval: 1000
        path: *bar_cmd
        args: ["cst"]
        content:  
          string: 
            text: "{clock}" 
            on-click: gnome-clocks

    - clock:
        time-format: "%H:%M"
        date-format: "%b %d %a"
        content:
          - string: {text: "{date}", right-margin: 5}
          - string: 
              text: "{time}"
              on-click: gnome-calendar

